Subject = [
{"revenue": "Fines", "weight": 500},
{"revenue": "Land Tax", "weight": 100},
{"revenue": "Payroll Tax", "weight": 100},
{"revenue": "Property Tax", "weight": 150},
{"revenue": "Royalties", "weight": 100},
{"revenue": "Gaming and Wagering", "weight": 100},
{"revenue": "Health Insurance Levy", "weight": 300},
{"revenue": "Insurance Duty", "weight": 250},
{"revenue": "Parking Space Levy", "weight": 50},
{"revenue": "Foreign Buyers and Land Owners", "weight": 100},
{"revenue": "Motor Vehicle Duty", "weight": 550},
{"revenue": "Passenger Service Levy", "weight": 100},
{"revenue": "Emergency Services Levy", "weight": 100},
{"revenue": "Income Tax equivalent Regime", "weight": 300},
{"revenue": "Traffic Violation Fines", "weight": 900},
{"revenue": "Ambulance Fees", "weight": 300},
{"revenue": "Customer Service Fees", "weight": 200},
{"revenue": "College Fees", "weight": 400},
{"revenue": "Council Fees", "weight": 800},
{"revenue": "Water Fees", "weight": 800},
{"revenue": "Workers Compensation Fees", "weight": 800},
{"revenue": "Advocates and Sponsors", "weight": 100},
{"revenue": "Support and Community Services", "weight": 100},
{"revenue": "First Home Buyers Assistance Schemes", "weight": 200},
{"revenue": "First Home Buyers (New Homes) Grants", "weight": 200},
{"revenue": "Shared Equity Home Buyer Helper", "weight": 100},
{"revenue": "Electric Vehicle Rebate", "weight": 100},
{"revenue": "Electric Vehicle Stamp Duty Refund", "weight": 100},
{"revenue": "Previous Schemes", "weight": 100},
{"revenue": "Search and make a claim", "weight": 100},
{"revenue": "Proof of Owndership", "weight": 100},
{"revenue": "Return Unclaimed Money", "weight": 700 }
]
